name: dialectos
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  audioplayers: ^0.19.1
  cloud_firestore: ^4.4.5
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_screenutil: ^5.7.0
  fpdart: ^0.6.0
  get: ^4.6.5
  google_sign_in: ^6.0.2
  loading_indicator: ^3.1.0
  shared_preferences: ^2.0.20

flutter_native_splash:
  background_image: "assets/images/splash.png"
  # flutter clean && flutter pub get && flutter pub run flutter_native_splash:create

flutter_icons: 
  image_path: "assets/images/app-icon.png"
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets: 
      - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin-100.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight-200.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light-300.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular-400.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium-500.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold-600.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold-700.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold-800.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black-900.ttf
          weight: 900
