// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6QsurlaHHDAzPBjlsRpv5Vsbdh-v15iw',
    appId: '1:167529806001:web:bbdfd5acd9b5b7fbf40a90',
    messagingSenderId: '167529806001',
    projectId: 'dialectos-3a996',
    authDomain: 'dialectos-3a996.firebaseapp.com',
    storageBucket: 'dialectos-3a996.appspot.com',
    measurementId: 'G-25D2V847SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD8BzSbqvBpg1o96mv91KJRbBWJzU5zDY',
    appId: '1:167529806001:android:8cb36b65fa77a23ff40a90',
    messagingSenderId: '167529806001',
    projectId: 'dialectos-3a996',
    storageBucket: 'dialectos-3a996.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB77jUMdLQtLAWSqmgvidfeD4ycquXfyWI',
    appId: '1:167529806001:ios:d431a9d34d74b9d9f40a90',
    messagingSenderId: '167529806001',
    projectId: 'dialectos-3a996',
    storageBucket: 'dialectos-3a996.appspot.com',
    iosClientId: '167529806001-r6bvtuqmk7hp5b35163iuuh9hq9hgsvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.dialektos',
  );
}
